[build]
  publish = "poker-pot-tracker-git-upload-cash-pot/outputs"
  functions = "poker-pot-tracker-git-upload-cash-pot/netlify/functions"

[[redirects]]
  from = "/"
  to = "/poker-pot-tracker.html"
  status = 200

[[redirects]]
  from = "/admin"
  to = "/admin.html"
  status = 200

[[redirects]]
  from = "/:sessionDate"
  to = "/poker-pot-tracker.html"
  status = 200
